# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'AgoraVoiceSdk' do
  
  use_frameworks!
  pod 'Floaty', '~> 4.2.0'  
  pod 'AGEVideoLayout', '~> 1.0.2'
  pod 'AgoraAudio_iOS', '3.5.0.1'
  pod 'AgoraMediaPlayer_iOS', '1.2.2'
end

target 'DemoVoice' do
  
  use_frameworks!
  pod 'Floaty', '~> 4.2.0'  
  pod 'AGEVideoLayout', '~> 1.0.2'
  pod 'AgoraAudio_iOS', '3.5.0.1'
  pod 'AgoraMediaPlayer_iOS', '1.2.2'
end

